---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: artifact.tar.gz
    dest: "~/backend_app/artifact.tar.gz"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend_app
    tar -xvf artifact.tar.gz
    ls .
    rm -rf artifact.tar.gz
- name: "Install dependencies for project"
  shell: |
    cd ~/backend_app
    ls .
    sudo npm install -g npm-install-peers
    sudo npm i -g pm2
    sudo pm2 stop default
    sudo pm2 start main.js 
  environment:     
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.js"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: 5432
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
