---
- name: "Creates backend app directory"
  file:
    path: ~/backend_app
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: artifact.tar.gz
    dest: "~/backend_app/artifact.tar.gz"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend_app
    tar -xvf artifact.tar.gz
    rm -rf artifact.tar.gz
- name: "Install dependencies for project"
  shell: |
    apt install nodejs npm
    cd ~/backend_app
    npm install
    pm2 stop default
    pm2 start npm --start
