---
- name: "Creates backend directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: artifact.tar.gz
    dest: "~/backend/artifact.tar.gz"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend
    tar -xvf artifact.tar.gz
    ls .
    rm -rf artifact.tar.gz
- name: "Install dependencies for project"
  shell: |
    cd ~/backend
    ls .
    npm install -g npm-install-peers
    npm i -g pm2
    pm2 stop default
    pm2 start npm -- start 
