---
- name: "Creates backend directory"
  file:
    path: ~/backend
    state: directory

- name: "Copy compiled backend app"
  copy:
    src: artifact.tar.gz
    dest: "~/backend/artifact.tar.gz"

- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend
    tar -xvf artifact.tar.gz
    ls .
    rm -rf artifact.tar.gz
- name: "Install dependencies for project"
  become: true
  shell: |
    cd /home/ubuntu/backend
    ls .
    npm install -g npm-install-peers
    npm i -g pm2   
- name: "start npm"
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm -- start
- name: "kill npm"
  become: true
  shell: |
    whoami > user.txt
    ss -tunlp > ports.txt
    ps -ef | grep -i pm2 > pid.txt
    ps -ef | grep -i pm2 | grep -v grep | awk '{print $2}' | xargs kill
    ps -ef | grep -i pm2 >> pid.txt
- name: "re-start npm"
  become: true
  shell: |
    cd /home/ubuntu/backend
    whoami > user02.txt
    pm2 start npm -- start
    ss -tunlp >> ports.txt
    ps -ef | grep -i pm2 >> pid.txt    
  environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
