version: 2.1

#commands:
#  destroy_environment:
#    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
#    parameters:
#       workflow_id:
#          type: string
      # Add parameter here   
#    steps:
#      - run:
#          name: Destroy environments
#          when: on_fail
#          command: |
#            echo "Destroying environment: <<parameters.workflow_id>> "
#            aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow_id>>
#            aws cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflow_id>>
jobs:
  configure_infrastructure:
    docker:
      # Docker image here that supports Ansible
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["27:a9:6d:58:e8:f2:78:ba:b3:9d:9d:dd:97:74:fe:49"]
      # attach workspace
      - attach_workspace:
          at: ~/
      - run:
          name: Install dependencies
          command: |
            apk add --update tar gzip
            apk add --no-cache python3 py3-pip && pip3 install --upgrade pip && pip3 install --no-cache-dir awscli && rm -rf /var/cache/apk/*
      - run:
          name: Configure server
          command: |
            cd .circleci/ansible
            ansible-playbook -i inventory.txt configure-server.yml
             
workflows:
 default:
  jobs:
    - configure_infrastructure      
      

